name: SimplePresents
version: '${project.version}'
main: net.azisaba.simplepresents.SimplePresents
author: pino223
api-version: '1.16'
softdepend: [CrackShot, MythicMobs]

commands:
  presents:
    description: プレゼント関連のコマンド
    usage: /presents <subcommand>
    aliases: ["sp"]